halflife.wad
cs_cbble.wad
cs_office.wad
de_piranesi.wad
gfx/env/blackup.tga
gfx/env/blackdn.tga
gfx/env/blacklf.tga
gfx/env/blackrt.tga
gfx/env/blackft.tga
gfx/env/blackbk.tga
sprites/maxpayne/glow01.spr
sprites/maxpayne/spotlight309.spr
sprites/glow01.spr
sprites/glow03.spr
sound/ambience/truck2.wav
sound/maxpayne/radio_police.wav
sound/maxpayne/city_ambience.wav
sound/maxpayne/klub_music.wav
models/maxpayne/vent_roof2.mdl
models/maxpayne/mentovskaya_mashina.mdl
models/maxpayne/derevo_tree1.mdl
models/maxpayne/zps_hotel_neon.mdl
models/maxpayne/provoda_cables_ceiling.mdl
models/maxpayne/telefon_phone.mdl
models/maxpayne/snow_car123.mdl
maps/zm_roscoe_street.txt
maps/zm_roscoe_street.res